name: Org GitHub Actions Usage Detail Report

on:
  workflow_dispatch:

jobs:
  analyze-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install PyGithub pyyaml tabulate

      - name: Run Detailed Actions Report
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ORG_NAME: DevCloudX  # replace
        run: python scripts/org_actions_detailed_report.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: gh-actions-detailed-report
          path: gh-actions-usage-summary.txt
